### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by sntran** [BrandExtract/spas-gphotos#1]
This package is not on NPM, and can't be install normally.

**Comment by jlafitte** [comment]
I think I just copied the readme from another plugin.  I thought you told me we didn't require a special plugin for this.

**Comment by sntran** [comment]
I was trying to get SPAS to run locally with our collection of bundles, and one of them requires this module.

**Comment by jlafitte** [comment]
I didn't know it was still in use.  I think you'll find it much easier just to use the bundle you are working on rather than all of them...

I don't have a problem uploading this to NPM, I just don't think it has much value.

**Comment by jlafitte** [comment]
https://www.npmjs.com/package/spas-gphotos
